[[mgr.prepend_keymap]]
on   = "!"
run  = 'shell "${SHELL}" --block --confirm'
desc = "Open the shell in current location"

[[mgr.prepend_keymap]]
on   = "T"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = "<C-d>"
run  = "plugin diff"
desc = "Diff the marked file with the one currently hovering"
